site_name: ac-library-mojo Docs
docs_dir: docs
site_dir: site
site_url: https://shogo314.github.io/ac-library-mojo/
repo_url: https://github.com/shogo314/ac-library-mojo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - version-selector

extra:
  version:
    provider: mike

nav:
  - ホーム: index.md
  - TIPs: tips.md
  - APIs:
    - apis/index.md
    - ext:
      - apis/ext/index.md
      - data_structure:
        - apis/ext/data_structure/index.md
        - avltree:
          - apis/ext/data_structure/avltree/index.md
          - AVLTree: apis/ext/data_structure/avltree/AVLTree.md
          - AVLTreeNode: apis/ext/data_structure/avltree/AVLTreeNode.md
          - AVLTreeNodePointer: apis/ext/data_structure/avltree/AVLTreeNodePointer.md
        - binarytrie:
          - apis/ext/data_structure/binarytrie/index.md
          - BinaryTrie: apis/ext/data_structure/binarytrie/BinaryTrie.md
          - BinaryTrieNode: apis/ext/data_structure/binarytrie/BinaryTrieNode.md
          - BinaryTrieNodePointer: apis/ext/data_structure/binarytrie/BinaryTrieNodePointer.md
        - dualsegtree:
          - apis/ext/data_structure/dualsegtree/index.md
          - DualSegTree: apis/ext/data_structure/dualsegtree/DualSegTree.md
          - RAddQ: apis/ext/data_structure/dualsegtree/RAddQ.md
          - RUpdateQ: apis/ext/data_structure/dualsegtree/RUpdateQ.md
        - interval_heap:
          - apis/ext/data_structure/interval_heap/index.md
          - IntervalHeap: apis/ext/data_structure/interval_heap/IntervalHeap.md
        - potentialized_unionfind:
          - apis/ext/data_structure/potentialized_unionfind/index.md
          - PotentializedUnionFind: apis/ext/data_structure/potentialized_unionfind/PotentializedUnionFind.md
          - UnionFindMul: apis/ext/data_structure/potentialized_unionfind/UnionFindMul.md
          - UnionFindPlus: apis/ext/data_structure/potentialized_unionfind/UnionFindPlus.md
        - priority_queue:
          - apis/ext/data_structure/priority_queue/index.md
          - PriorityQueue: apis/ext/data_structure/priority_queue/PriorityQueue.md
          - heap_max: apis/ext/data_structure/priority_queue/heap_max.md
          - heap_min: apis/ext/data_structure/priority_queue/heap_min.md
        - wordsizetree:
          - apis/ext/data_structure/wordsizetree/index.md
          - WordSizeTree: apis/ext/data_structure/wordsizetree/WordSizeTree.md
      - dp:
        - apis/ext/dp/index.md
        - knapsack_problem:
          - apis/ext/dp/knapsack_problem/index.md
          - knapsack: apis/ext/dp/knapsack_problem/knapsack.md
          - knapsack_01: apis/ext/dp/knapsack_problem/knapsack_01.md
        - levenshtein_distance_problem:
          - apis/ext/dp/levenshtein_distance_problem/index.md
          - edit_distance: apis/ext/dp/levenshtein_distance_problem/edit_distance.md
          - levenshtein_distance: apis/ext/dp/levenshtein_distance_problem/levenshtein_distance.md
        - longest_increasing_subsequence_problem:
          - apis/ext/dp/longest_increasing_subsequence_problem/index.md
          - longest_increasing_subsequence: apis/ext/dp/longest_increasing_subsequence_problem/longest_increasing_subsequence.md
      - math:
        - apis/ext/math/index.md
        - affine:
          - apis/ext/math/affine/index.md
          - Affine: apis/ext/math/affine/Affine.md
    - py:
      - apis/py/index.md
      - bisect:
        - apis/py/bisect/index.md
        - bisect_left: apis/py/bisect/bisect_left.md
        - bisect_right: apis/py/bisect/bisect_right.md
      - builtin:
        - apis/py/builtin/index.md
        - pow_mod: apis/py/builtin/pow_mod.md
      - heapq:
        - apis/py/heapq/index.md
        - heapify: apis/py/heapq/heapify.md
        - heappop: apis/py/heapq/heappop.md
        - heappush: apis/py/heapq/heappush.md
        - heappushpop: apis/py/heapq/heappushpop.md
        - heapreplace: apis/py/heapq/heapreplace.md
      - itertools:
        - apis/py/itertools/index.md
      - math:
        - apis/py/math/index.md
        - isqrt: apis/py/math/isqrt.md
      - operator:
        - apis/py/operator/index.md
        - add: apis/py/operator/add.md
        - gt: apis/py/operator/gt.md
        - inv: apis/py/operator/inv.md
        - lt: apis/py/operator/lt.md
        - max_: apis/py/operator/max_.md
        - min_: apis/py/operator/min_.md
        - mul: apis/py/operator/mul.md
        - neg: apis/py/operator/neg.md
        - truediv: apis/py/operator/truediv.md
      - sympy:
        - apis/py/sympy/index.md
        - isprime: apis/py/sympy/isprime.md
    - convolution:
      - apis/convolution/index.md
      - convolution_int: apis/convolution/convolution_int.md
      - convolution_mod: apis/convolution/convolution_mod.md
    - dsu:
      - apis/dsu/index.md
      - DSU: apis/dsu/DSU.md
    - fenwicktree:
      - apis/fenwicktree/index.md
      - FenwickTree: apis/fenwicktree/FenwickTree.md
    - io:
      - apis/io/index.md
      - IO: apis/io/IO.md
    - lazysegtree:
      - apis/lazysegtree/index.md
      - LazySegTree: apis/lazysegtree/LazySegTree.md
      - AddMonoidHasLt: apis/lazysegtree/AddMonoidHasLt.md
      - RAddMaxQ: apis/lazysegtree/RAddMaxQ.md
      - RAddMinQ: apis/lazysegtree/RAddMinQ.md
      - RAddSumQ: apis/lazysegtree/RAddSumQ.md
      - RUpdateMaxQ: apis/lazysegtree/RUpdateMaxQ.md
      - RUpdateMinQ: apis/lazysegtree/RUpdateMinQ.md
      - RUpdateSumQ: apis/lazysegtree/RUpdateSumQ.md
    - math:
      - apis/math/index.md
      - crt: apis/math/crt.md
      - floor_sum: apis/math/floor_sum.md
      - inv_mod: apis/math/inv_mod.md
    - maxflow:
      - apis/maxflow/index.md
      - MFEdge: apis/maxflow/MFEdge.md
      - MFGraph: apis/maxflow/MFGraph.md
      - Capable: apis/maxflow/Capable.md
    - metadata:
      - apis/metadata/index.md
      - get_version: apis/metadata/get_version.md
    - method_traits:
      - apis/method_traits/index.md
      - AddGroup: apis/method_traits/AddGroup.md
      - AddMonoid: apis/method_traits/AddMonoid.md
      - Field: apis/method_traits/Field.md
      - HasAdd: apis/method_traits/HasAdd.md
      - HasEq: apis/method_traits/HasEq.md
      - HasEqCollectionElement: apis/method_traits/HasEqCollectionElement.md
      - HasInitInt: apis/method_traits/HasInitInt.md
      - HasInitStringRaising: apis/method_traits/HasInitStringRaising.md
      - HasInitStringRaisingCollectionElement: apis/method_traits/HasInitStringRaisingCollectionElement.md
      - HasLtCollectionElement: apis/method_traits/HasLtCollectionElement.md
      - HasMul: apis/method_traits/HasMul.md
      - HasNeg: apis/method_traits/HasNeg.md
      - HasSub: apis/method_traits/HasSub.md
      - HasTruediv: apis/method_traits/HasTruediv.md
      - Invable: apis/method_traits/Invable.md
      - MulGroup: apis/method_traits/MulGroup.md
      - MulMonoid: apis/method_traits/MulMonoid.md
      - Ring: apis/method_traits/Ring.md
      - SemiRing: apis/method_traits/SemiRing.md
    - mincostflow:
      - apis/mincostflow/index.md
      - MCFEdge: apis/mincostflow/MCFEdge.md
      - MCFGraph: apis/mincostflow/MCFGraph.md
    - modint:
      - apis/modint/index.md
      - StaticModint: apis/modint/StaticModint.md
    - scc:
      - apis/scc/index.md
      - SCCGraph: apis/scc/SCCGraph.md
    - segtree:
      - apis/segtree/index.md
      - SegTree: apis/segtree/SegTree.md
      - RMaxQ: apis/segtree/RMaxQ.md
      - RMinQ: apis/segtree/RMinQ.md
      - RMulQ: apis/segtree/RMulQ.md
      - RSumQ: apis/segtree/RSumQ.md
      - max_right: apis/segtree/max_right.md
      - min_left: apis/segtree/min_left.md
    - string:
      - apis/string/index.md
      - lcp_array: apis/string/lcp_array.md
      - string_to_list: apis/string/string_to_list.md
      - suffix_array: apis/string/suffix_array.md
      - z_algorithm: apis/string/z_algorithm.md
    - twosat:
      - apis/twosat/index.md
      - TwoSat: apis/twosat/TwoSat.md
  - ベンチマーク: benchmark.md
  - コントリビュート: contribute.md
  - ライセンス: license.md

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            ホーム: Home
            ベンチマーク: Benchmark
            コントリビュート: Contribute
            ライセンス: License

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: .mkdocs/macros.tex
  - admonition:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - pymdownx.inlinehilite:
  - pymdownx.details:
  - pymdownx.emoji:
