site_name: ac-library-mojo Docs
docs_dir: docs
site_dir: site
site_url: https://shogo314.github.io/ac-library-mojo/
repo_url: https://github.com/shogo314/ac-library-mojo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - version-selector

extra:
  version:
    provider: mike

nav:
  - ホーム: index.md
  - モジュール:
    - modules/index.md
    - convolution:
      - modules/convolution/index.md
    - dsu:
      - modules/dsu/index.md
    - fenwicktree:
      - modules/fenwicktree/index.md
    - io:
      - modules/io/index.md
    - lazysegtree:
      - modules/lazysegtree/index.md
    - math:
      - modules/math/index.md
    - maxflow:
      - modules/maxflow/index.md
    - method_traits:
      - modules/method_traits/index.md
    - mincostflow:
      - modules/mincostflow/index.md
    - modint:
      - modules/modint/index.md
    - scc:
      - modules/scc/index.md
    - segtree:
      - modules/segtree/index.md
    - string:
      - modules/string/index.md
    - twosat:
      - modules/twosat/index.md
    - py:
      - bisect:
        - modules/py/bisect/index.md
      - builtin:
        - modules/py/builtin/index.md
      - heapq:
        - modules/py/heapq/index.md
      - itertools:
        - modules/py/itertools/index.md
      - math:
        - modules/py/math/index.md
      - operator:
        - modules/py/operator/index.md
      - string:
        - modules/py/string/index.md
      - sympy:
        - modules/py/sympy/index.md
    - ext:
      - affine:
        - modules/ext/affine/index.md
      - algorithm:
        - modules/ext/algorithm/index.md
      - avltree:
        - modules/ext/avltree/index.md
      - dualsegtree:
        - modules/ext/dualsegtree/index.md
      - interval_heap:
        - modules/ext/interval_heap/index.md
      - potentialized_unionfind:
        - modules/ext/potentialized_unionfind/index.md
      - priority_queue:
        - modules/ext/priority_queue/index.md
      - string:
        - modules/ext/string/index.md
  - ベンチマーク: benchmark.md
  - コントリビュート: contribute.md
  - ライセンス: license.md

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            ホーム: Home
            モジュール: Modules
            ベンチマーク: Benchmark
            コントリビュート: Contribute
            ライセンス: License

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex
  - admonition:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - pymdownx.inlinehilite:
  - pymdownx.details:
  - pymdownx.emoji:
  - codehilite:
      guess_lang: false
