[languages.mojo]
compile = "magic run mojo build -o {tempdir}/a.out {path} -I {basedir} -D ASSERT=warn"
execute = "{tempdir}/a.out"
bundle = "false"
list_dependencies = "python3 .verify-helper/list_dependencies.py {path}"
verification_file_suffix = ".test.mojo"
